# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbded782a051608658eb50ba6d9ca70f0140c8875e2149feaf5460b36bf0d36c0e6f79fdc4adf1dde18b9f1a501575f4d75584c7b291a6593d13738e2cf57768

test:
  secret_key_base: 7d6a60b772f113daa14ec6a6a33df70d1d02d2920f008f596b5598e83a1abfcd6a083d5ac50f058ca5ebf3c7e0f7a4ef2ca6391920098ed63b04c8c85f6552b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
